apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-deployment
  name: nginx-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-deployment
  type: NodePort
