apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: “1”
  labels:
    run: nginx-deployment
  name: nginx-deployment
  namespace : web
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: nginx-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginx-deployment
    spec:
      containers:
      - env:
        - name: NGINX_PORT
          value: “80"
        image: nginx:1.16
        name: nginx
